MOV SI,8000H     
MOV CL,0AH     
MOV DL,02H       
MOV DI,9000H    
SEARCH_LOOP:MOV AL,[SI]  
CMP AL,DL    
JE FOUND     
INC SI      
DEC CL       
JNZ SEARCH_LOOP
MOV AL,00H   
MOV [DI],AL  
HLT
FOUND: MOV AL,0FFH  
MOV [DI],AL 
HLT